<a href="https://colab.research.google.com/github/AshvinVignesh/Sentiment-Analysis/blob/master/model/SA_SINHALA_3_CONTD(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SA FOR CON_EMOJI_MEANING**

In [ ]:
import pandas as pd 

In [ ]:
df = pd.read_csv('cleaned.csv')

In [ ]:
df.head(10)

Text      Class  \
0        ඝරසරප චිත්‍රපටය පහළ තියෙන එකෙන් කරගන්න         Neutral   
1               මොකක් හරි නාට්‍යයක් තියෙන්නත් එපැයි     Neutral   
2       කිමද තරම් කොහේදෝ විදපු ගලක් උරන මා මිතුරු...    Neutral   
3       එහෙම කොහොමද උනේ  😂  පරය අපිව අයින් කරල නේ  😂    Neutral   
4   විමලයා ගොනෙක් වගෙ එකෙ මෑරෙන්න හදනවා පරය රටට ව...  Political   
5      ලැජ්ජයි ස⁣හෝදරයා විදිහ දැක්කාම ඔබලාගේ කුලල...     Racist   
6    ලැජ්ජයි ස⁣හෝදරයා විදිහ දැක්කාම ඔබලාගේ කුලල්ක...     Racist   
7      මං තම්බි වගේද පෙන්නෙ 😏  මං බ්‍රහස්පතින්දා ...    Neutral   
8     ඉටිම් බං උතුර ඉල්ලනසෙට් එකයි නැගෙනහිරපඉල්ලන...     Racist   
9      පේනවානේ තම්බි කවදත් ඉන්නේ උන්ට වාසි පැත්තේ...     Racist   

                                            PureText ConEmoji Emojis  \
0        ඝරසරප චිත්‍රපටය පහළ තියෙන එකෙන් කරගන්න           NaN    NaN   
1         මොකක් හරි නාට්‍යයක් තියෙන්නත් එපැයි ඉතින්       NaN    NaN   
2       කිමද මේ තරම් කොහේදෝ ඇති විදපු ගලක් හා උරන...      NaN    NaN   
3         එහෙම කොහොමද උනේ    පරය අපිව අයින් කරල නේ        😂 😂    😂 😂   
4   විමලයා ගොනෙක් වගෙ එකෙ මෑරෙන්න හදනවා පරය රටට ව...      NaN    NaN   
5      ලැජ්ජයි ස⁣හෝදරයා මේ යන විදිහ දැක්කාම ඔබලාග...      NaN    NaN   
6    ලැජ්ජයි ස⁣හෝදරයා මේ යන විදිහ දැක්කාම ඔබලාගේ ...      NaN    NaN   
7      ඇයි මං තම්බි වගේද පෙන්නෙ   මං බ්‍රහස්පතින්...      😏 😅    😏 😅   
8     ඉටිම් බං උතුර ඉල්ලනසෙට් එකයි නැගෙනහිරපඉල්ලන...      NaN    NaN   
9      පේනවානේ තම්බි කවදත් ඉන්නේ උන්ට වාසි පැත්තේ...      NaN    NaN   

                  Con_emoji_meanings  
0                                NaN  
1                                NaN  
2                                NaN  
3      face tears joy face tears joy  
4                                NaN  
5                                NaN  
6                                NaN  
7  smirking face grinning face sweat  
8                                NaN  
9                                NaN

In [ ]:
DF = df.drop(['Text','PureText',	'ConEmoji',	'Emojis'], axis=1)

In [ ]:
DF = DF.dropna()

In [ ]:
DF.info

<bound method DataFrame.info of           Class                            Con_emoji_meanings
3       Neutral                 face tears joy face tears joy
7       Neutral             smirking face grinning face sweat
19      Neutral                loudly crying face crying face
23      Neutral                                face tears joy
24       Racist                                  smiling face
...         ...                                           ...
1588   Religion                                    angry face
1589  Political  face tears joy face tears joy face tears joy
1590     Racist                                grimacing face
1591   Religion                                face tears joy
1592  Political                        smiling face hearteyes

[424 rows x 2 columns]>

In [ ]:
# from textblob import TextBlob
# from nltk.tokenize import word_tokenize
# from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# stemmer = PorterStemmer()
# def stemming(data):
#     text = [stemmer.stem(word) for word in data]
#     return data

In [ ]:
# DF['Con_emoji_meanings'] = DF['Con_emoji_meanings'].apply(lambda x: stemming(x))

In [ ]:
DF.head(10)

Class                                 Con_emoji_meanings
3    Neutral                      face tears joy face tears joy
7    Neutral                  smirking face grinning face sweat
19   Neutral                     loudly crying face crying face
23   Neutral                                     face tears joy
24    Racist                                       smiling face
32  Religion  smiling face hearteyes grinning face smiling f...
42  Religion                                       neutral face
44   Neutral                                       pouting face
48   Neutral                          beaming face smiling eyes
56   Neutral                                     face tears joy

remove stop words

In [ ]:
from gensim.parsing.preprocessing import remove_stopwords


DF['Con_emoji_meanings']=DF['Con_emoji_meanings'].apply(lambda x : remove_stopwords(x))

In [ ]:
DF.head(10)

Class                                 Con_emoji_meanings
3    Neutral                      face tears joy face tears joy
7    Neutral                  smirking face grinning face sweat
19   Neutral                     loudly crying face crying face
23   Neutral                                     face tears joy
24    Racist                                       smiling face
32  Religion  smiling face hearteyes grinning face smiling f...
42  Religion                                       neutral face
44   Neutral                                       pouting face
48   Neutral                          beaming face smiling eyes
56   Neutral                                     face tears joy

# **TOKENIZE AND STEMMIMING**

In [ ]:
import pandas as pd
import nltk
from nltk.stem import PorterStemmer

# download necessary nltk resources (only needed once)
nltk.download('punkt')

# create a stemmer object
stemmer = PorterStemmer()

# define a DataFrame with text data
data = pd.DataFrame({'text': ['I am running in the park and seeing a lot of runners',
                              'She is walking her dog in the neighborhood']})

# apply tokenization and stemming to the text column of the DataFrame
data['tokens'] = data['text'].apply(nltk.word_tokenize)
data['stemmed_tokens'] = data['tokens'].apply(lambda x: [stemmer.stem(word) for word in x])

# join the stemmed tokens back into a sentence without commas
data['stemmed_text'] = data['stemmed_tokens'].apply(lambda x: " ".join(x))

# print the original text and the stemmed text
print("Original DataFrame:\n", data[['text']])
print("Stemmed DataFrame:\n", data[['stemmed_text']])


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Original DataFrame:
                                                 text
0  I am running in the park and seeing a lot of r...
1         She is walking her dog in the neighborhood
Stemmed DataFrame:
                                    stemmed_text
0  i am run in the park and see a lot of runner
1       she is walk her dog in the neighborhood


In [ ]:
DF['Con_emoji_meanings'] = DF['Con_emoji_meanings'].apply(nltk.word_tokenize)

In [ ]:
DF['Con_emoji_meanings'] = DF['Con_emoji_meanings'].apply(lambda x: [stemmer.stem(word) for word in x])


In [ ]:
DF['Con_emoji_meanings'] = DF['Con_emoji_meanings'].apply(lambda x: " ".join(x))

In [ ]:
DF.head(10)

Class                               Con_emoji_meanings
3    Neutral                      face tear joy face tear joy
7    Neutral                       smirk face grin face sweat
19   Neutral                         loudli cri face cri face
23   Neutral                                    face tear joy
24    Racist                                       smile face
32  Religion  smile face heartey grin face smile face heartey
42  Religion                                     neutral face
44   Neutral                                        pout face
48   Neutral                              beam face smile eye
56   Neutral                                    face tear joy

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [ ]:
max_features = 1500
count_vector = CountVectorizer(max_features = max_features)  
X1= count_vector.fit_transform(DF['Con_emoji_meanings']).toarray() 
X1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
f = pd.DataFrame(X1,columns=count_vector.get_feature_names())
f

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


angri  anguish  astonish  beam  big  blow  broken  cat  confound  confus  \
0        0        0         0     0    0     0       0    0         0       0   
1        0        0         0     0    0     0       0    0         0       0   
2        0        0         0     0    0     0       0    0         0       0   
3        0        0         0     0    0     0       0    0         0       0   
4        0        0         0     0    0     0       0    0         0       0   
..     ...      ...       ...   ...  ...   ...     ...  ...       ...     ...   
419      1        0         0     0    0     0       0    0         0       0   
420      0        0         0     0    0     0       0    0         0       0   
421      0        0         0     0    0     0       0    0         0       0   
422      0        0         0     0    0     0       0    0         0       0   
423      0        0         0     0    0     0       0    0         0       0   

     ...  smile  smirk  squint  steam  sunglass  sweat  tear  tongu  weari  \
0    ...      0      0       0      0         0      0     2      0      0   
1    ...      0      1       0      0         0      1     0      0      0   
2    ...      0      0       0      0         0      0     0      0      0   
3    ...      0      0       0      0         0      0     1      0      0   
4    ...      1      0       0      0         0      0     0      0      0   
..   ...    ...    ...     ...    ...       ...    ...   ...    ...    ...   
419  ...      0      0       0      0         0      0     0      0      0   
420  ...      0      0       0      0         0      0     3      0      0   
421  ...      0      0       0      0         0      0     0      0      0   
422  ...      0      0       0      0         0      0     1      0      0   
423  ...      1      0       0      0         0      0     0      0      0   

     wink  
0       0  
1       0  
2       0  
3       0  
4       0  
..    ...  
419     0  
420     0  
421     0  
422     0  
423     0  

[424 rows x 45 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# convert classes to number
encoder = LabelEncoder()
y1 = encoder.fit_transform(DF['Class'])
y1

array([0, 0, 0, 0, 2, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4,
       4, 4, 2, 4, 4, 1, 0, 4, 0, 0, 2, 4, 4, 4, 4,

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix,classification_report,ConfusionMatrixDisplay

In [ ]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1,y1, test_size =0.2, random_state=42)

# **RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, random_state=0, class_weight={0:0.11 ,1: 0.12 ,2:0.67 ,3: 0.03, 4:0.05})  
rf.fit(X1_train, y1_train)

print("Training Accuracy :" , accuracy_score(y1_train, rf.predict(X1_train))*100 )

predictions2 = rf.predict(X1_test)
#print(confusion_matrix(Y_test,predictions2))  
print(classification_report(y1_test,predictions2))  
print("TEST ACCURACY  : ",accuracy_score(y1_test, predictions2)*100)

Training Accuracy : 71.68141592920354
              precision    recall  f1-score   support

           0       0.77      0.88      0.82        64
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.22      0.67      0.33         3

    accuracy                           0.68        85
   macro avg       0.16      0.26      0.19        85
weighted avg       0.59      0.68      0.63        85

TEST ACCURACY  :  68.23529411764706


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **HYPERPARAMETER FOR RANDOM FOREST**

In [ ]:
rf_hy = RandomForestClassifier(random_state=42, n_jobs=-1, n_estimators=10)
rf_hy.fit(X1_train, y1_train)
print("Training Accuracy :" , accuracy_score(y1_train, rf_hy.predict(X1_train))*100 )

predictions2 = rf_hy.predict(X1_test)
#print(confusion_matrix(Y_test,predictions2))  
print(classification_report(y1_test,predictions2))  
print("TEST ACCURACY  : ",accuracy_score(y1_test, predictions2)*100)

Training Accuracy : 75.51622418879056
              precision    recall  f1-score   support

           0       0.74      0.94      0.83        64
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         3

    accuracy                           0.71        85
   macro avg       0.12      0.16      0.14        85
weighted avg       0.56      0.71      0.62        85

TEST ACCURACY  :  70.58823529411765


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **DECISION TREE**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy',splitter='best', class_weight={0:0.11 ,1: 0.12 ,2:0.67 ,3: 0.03, 4:0.05 },max_features='auto')
dt.fit(X1_train, y1_train)

print("Training Accuracy :" , accuracy_score(y1_train, dt.predict(X1_train))*100 )

predictions4 = dt.predict(X1_test)
#print(confusion_matrix(Y_test,predictions4))  
print(classification_report(y1_test,predictions4,zero_division=1))  
print("TEST ACCURACY SCORE : ",accuracy_score(y1_test, predictions4)*100)

Training Accuracy : 65.48672566371681
              precision    recall  f1-score   support

           0       0.83      0.78      0.81        64
           1       1.00      0.20      0.33         5
           2       0.00      0.00      0.00         4
           3       1.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.10      0.67      0.17         3

    accuracy                           0.62        85
   macro avg       0.49      0.27      0.22        85
weighted avg       0.71      0.62      0.63        85

TEST ACCURACY SCORE :  62.35294117647059


In [ ]:
dt.tree_.max_depth

27

# **HYPER PARAMETER TUNNING FOR DECISION TREE**

max depth =3

In [ ]:
dt = DecisionTreeClassifier(max_depth =3 , random_state=42)
dt.fit(X1_train, y1_train)
print("Training Accuracy :" , accuracy_score(y1_train, dt.predict(X1_train))*100 )

predictions4 = dt.predict(X1_test)
#print(confusion_matrix(Y_test,predictions4))  
print(classification_report(y1_test,predictions4,zero_division=1))  
print("TEST ACCURACY SCORE : ",accuracy_score(y1_test, predictions4)*100)

Training Accuracy : 71.38643067846607
              precision    recall  f1-score   support

           0       0.75      0.97      0.84        64
           1       1.00      0.00      0.00         5
           2       1.00      0.00      0.00         4
           3       1.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         3

    accuracy                           0.73        85
   macro avg       0.62      0.16      0.14        85
weighted avg       0.69      0.73      0.64        85

TEST ACCURACY SCORE :  72.94117647058823


In [ ]:
dt.tree_.max_depth

3

max_leaf_nodes =30

In [ ]:
dt = DecisionTreeClassifier( max_leaf_nodes =30, random_state=42)
dt.fit(X1_train, y1_train)
print("Training Accuracy :" , accuracy_score(y1_train, dt.predict(X1_train))*100 )

predictions4 = dt.predict(X1_test)
#print(confusion_matrix(Y_test,predictions4))  
print(classification_report(y1_test,predictions4,zero_division=1))  
print("TEST ACCURACY SCORE : ",accuracy_score(y1_test, predictions4)*100)

Training Accuracy : 75.22123893805309
              precision    recall  f1-score   support

           0       0.74      0.94      0.83        64
           1       1.00      0.00      0.00         5
           2       1.00      0.00      0.00         4
           3       1.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         3

    accuracy                           0.71        85
   macro avg       0.62      0.16      0.14        85
weighted avg       0.69      0.71      0.62        85

TEST ACCURACY SCORE :  70.58823529411765


# **Ada Boost Classifier + Decision Tree**

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=100 , base_estimator= dt)
abc.fit(X1_train,y1_train)

print("Training Accuracy :" , accuracy_score(y1_train, abc.predict(X1_train))*100)

predictions5 = abc.predict(X1_test)
print(confusion_matrix(y1_test,predictions5))
print(classification_report(y1_test,predictions5))
print("TEST ACCURACY : ",accuracy_score(y1_test, predictions5)*100)

Training Accuracy : 68.73156342182891
[[54  0  0  0  2  8]
 [ 4  0  0  0  0  1]
 [ 4  0  0  0  0  0]
 [ 1  0  0  0  0  1]
 [ 5  0  0  0  0  2]
 [ 2  0  0  0  0  1]]
              precision    recall  f1-score   support

           0       0.77      0.84      0.81        64
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.08      0.33      0.12         3

    accuracy                           0.65        85
   macro avg       0.14      0.20      0.16        85
weighted avg       0.58      0.65      0.61        85

TEST ACCURACY :  64.70588235294117


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **SVM**

In [ ]:
from sklearn.svm import LinearSVC
sv = LinearSVC(class_weight={0:0.11 ,1: 0.12 ,2:0.67 ,3: 0.03, 4:0.05 })
sv.fit(X1_train, y1_train)

print("Training Accuracy :" , accuracy_score(y1_train, sv.predict(X1_train))*100 )

predictions3 = sv.predict(X1_test)
#print(confusion_matrix(Y_test,predictions3))  
print(classification_report(y1_test,predictions3,zero_division=1))  
print(" TEST ACCURACY : ",accuracy_score(y1_test, predictions3)*100)

Training Accuracy : 68.43657817109144
              precision    recall  f1-score   support

           0       0.77      0.91      0.83        64
           1       1.00      0.00      0.00         5
           2       1.00      0.00      0.00         4
           3       1.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.22      0.67      0.33         3

    accuracy                           0.71        85
   macro avg       0.67      0.26      0.19        85
weighted avg       0.72      0.71      0.64        85

 TEST ACCURACY :  70.58823529411765


In [ ]:
from sklearn.svm import LinearSVC
sv = LinearSVC(random_state=42)
sv.fit(X1_train, y1_train)

print("Training Accuracy :" , accuracy_score(y1_train, sv.predict(X1_train))*100 )

predictions3 = sv.predict(X1_test)
#print(confusion_matrix(Y_test,predictions3))  
print(classification_report(y1_test,predictions3,zero_division=1))  
print(" TEST ACCURACY : ",accuracy_score(y1_test, predictions3)*100)

Training Accuracy : 73.15634218289085
              precision    recall  f1-score   support

           0       0.74      0.95      0.84        64
           1       1.00      0.00      0.00         5
           2       1.00      0.00      0.00         4
           3       1.00      0.00      0.00         2
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         3

    accuracy                           0.72        85
   macro avg       0.62      0.16      0.14        85
weighted avg       0.69      0.72      0.63        85

 TEST ACCURACY :  71.76470588235294


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [ ]:
import numpy as np

 SCALE  TRAINING  DATASETS 

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X1_train.astype(np.float32))
X_test_scaled = scaler.transform(X1_test.astype(np.float32))
lin_clf = LinearSVC(random_state=42)
lin_clf.fit(X_train_scaled, y1_train)
y_pred = lin_clf.predict(X_train_scaled)
print(accuracy_score(y1_train, y_pred)*100)

73.74631268436578


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


## **use kernels**
Kernels are a way in ML to add more flexibility to the algorithm by adding the polynomial degree of the dataset without increasing the features

In [ ]:
from sklearn.svm import SVC
svm_clf = SVC(gamma='scale')
svm_clf.fit(X_train_scaled[:10000], y1_train[:10000]) # We use an SVC with an RBF kernel
y_pred = svm_clf.predict(X_train_scaled)
print(accuracy_score(y1_train, y_pred)*100)

72.86135693215338
